services:
  - type: web
    name: latako-stebejimas
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: latakas-2c957c92-ku-7312.l.aivencloud.com
      - key: DB_PORT
        value: 26099
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_O218wwrMWicUdZRG7EK
      - key: DB_NAME
        value: defaultdb
      - key: PORT
        value: 10000
      - key: WS_PORT
        value: 8080